name: deployment from github to AWS
on:
  pull_request:
    branches:
      - master
    types:
      - closed
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: package code
        run: zip -r deploy.zip * -x '*.git*' ''
      - name: deploy to beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ vars.APP_NAME }}
          environment_name: ${{ vars.BEANSTALK_ENV_NAME }}
          version_label: "${{ github.event.pull_request.head.sha }}"
          region: ${{ vars.AWS_REGION }}
          deployment_package: deploy.zip
